FROM bitnami/spark:3.4.3

USER root

# Instala Python 3.7
RUN apt update && \
    apt install -y python3.7 python3.7-distutils python3.7-venv && \
    ln -sf /usr/bin/python3.7 /usr/bin/python && \
    apt clean

# Define las variables de entorno para PySpark
ENV PYSPARK_PYTHON=/usr/bin/python3.7
ENV PYSPARK_DRIVER_PYTHON=/usr/bin/python3.7
